version: "3.6"
services:
  web:
    build: .
    image: mens-book-breakfast-web-app
    container_name: web
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - MONGO_USER=user
      - MONGO_PASSWORD=password
    env_file:
      - ./src/config/config.env
    volumes:
      - ./src:/src:ro
      - ./src/node_modules
    depends_on:
      - mongo
    command: npm run dev
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
      - ./src/config/db_init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    container_name: mongo_db_ui
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
volumes:
  db_data:
